routes/web.php
<?php
//here are our routes that are used for Law project
Auth::routes();
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\LoginController@logout']);


Route::get('/{slug?}', ['as' => 'home', 'uses' => 'HomeController@index', 'middleware' => 'maintenance']);
// get cities by country id
Route::get('/cities/autocomplete', ['as' => 'cities.autocomplete', 'uses' => 'HomeController@autoCities', 'middleware' => 'maintenance']);
Route::get('/cities/{id}', ['as' => 'home.cities', 'uses' => 'HomeController@getCities', 'middleware' => 'maintenance']);
// Posts
Route::get('/posts/{id?}', ['as' => 'posts', 'uses' => 'PostController@index']);
Route::get('/post/seats/{id}', ['as' => 'post.seats', 'uses' => 'PostController@seats']);

// General
Route::get('search', ['as' => 'search', 'uses' => 'SearchController@index']);

// Muntazim Routes
Route::group(['prefix' => 'muntazim', 'middleware' => ['permissions']], function () {

    // Settings
    Route::get('/settings', ['as' => 'muntazim.settings', 'uses' => 'Muntazim\SettingController@index',
        'permissions' => \App\Models\Setting::modulePermissions(true, 'manage')]);
    Route::put('/settings/update', ['as' => 'muntazim.settings.update', 'uses' => 'Muntazim\SettingController@update',
        'permissions' => \App\Models\Setting::modulePermissions(true, 'edit')]);

    // Users
    Route::get('/users', ['as' => 'muntazim.users', 'uses' => 'Dashboard\UserController@index',
        'permissions' => \App\Models\User::modulePermissions(true, 'manage')]);
    Route::get('/users/show/{id}', ['as' => 'muntazim.users.show', 'uses' => 'Dashboard\UserController@show',
        'permissions' => \App\Models\Role::modulePermissions(true, 'show')]);
    Route::get('/user/create', ['as' => 'muntazim.user.create', 'uses' => 'Dashboard\UserController@create',
        'permissions' => \App\Models\User::modulePermissions(true, 'create')]);
    Route::get('/user/assign', ['as' => 'muntazim.user.assign', 'uses' => 'Dashboard\UserController@assign',
        'permissions' => \App\Models\Role::modulePermissions(true, 'assign')]);
    Route::post('/user/store', ['as' => 'muntazim.user.store', 'uses' => 'Dashboard\UserController@store',
        'permissions' => \App\Models\User::modulePermissions(true, 'store')]);
    Route::get('/user/edit/{id}', ['as' => 'muntazim.user.edit', 'uses' => 'Dashboard\UserController@edit',
        'permissions' => \App\Models\User::modulePermissions(true, 'edit')]);
    Route::put('/user/update/{id}', ['as' => 'muntazim.user.update', 'uses' => 'Dashboard\UserController@update',
        'permissions' => \App\Models\User::modulePermissions(true, 'update')]);
    Route::get('/user/delete/{id}', ['as' => 'muntazim.user.delete', 'uses' => 'Dashboard\UserController@destroy',
        'permissions' => \App\Models\User::modulePermissions(true, 'delete')]);
    // Roles
    Route::get('/roles', ['as' => 'muntazim.roles', 'uses' => 'Muntazim\RoleController@index',
        'permissions' => \App\Models\Role::modulePermissions(true, 'manage')]);
    Route::get('/roles/show/{id}', ['as' => 'muntazim.roles.show', 'uses' => 'Muntazim\RoleController@show',
        'permissions' => \App\Models\Role::modulePermissions(true, 'show')]);
    Route::get('/role/create', ['as' => 'muntazim.roles.create', 'uses' => 'Muntazim\RoleController@create',
        'permissions' => \App\Models\Role::modulePermissions(true, 'create')]);
    Route::get('/role/assign', ['as' => 'muntazim.roles.assign', 'uses' => 'Muntazim\RoleController@assign',
        'permissions' => \App\Models\Role::modulePermissions(true, 'assign')]);
    Route::post('/role/store', ['as' => 'muntazim.roles.store', 'uses' => 'Muntazim\RoleController@store',
        'permissions' => \App\Models\Role::modulePermissions(true, 'store')]);
    Route::get('/role/edit/{id}', ['as' => 'muntazim.roles.edit', 'uses' => 'Muntazim\RoleController@edit',
        'permissions' => \App\Models\Role::modulePermissions(true, 'edit')]);
    Route::put('/role/update/{id?}', ['as' => 'muntazim.roles.update', 'uses' => 'Muntazim\RoleController@update',
        'permissions' => \App\Models\Role::modulePermissions(true, 'update')]);
    Route::get('/role/delete/{id}', ['as' => 'muntazim.roles.delete', 'uses' => 'Muntazim\RoleController@destroy',
        'permissions' => \App\Models\User::modulePermissions(true, 'delete')]);
    //permissions
    Route::get('/permissions', ['as' => 'muntazim.permissions', 'uses' => 'Muntazim\PermissionController@index',
        'permissions' => \App\Models\Permission::modulePermissions(true, 'manage')]);
    Route::get('/permissions/show/{id}', ['as' => 'muntazim.permissions.show', 'uses' => 'Muntazim\PermissionController@show',
        'permissions' => \App\Models\Role::modulePermissions(true, 'show')]);
    Route::get('/permissions/assign', ['as' => 'muntazim.permissions.assign', 'uses' => 'Muntazim\PermissionController@assign',
        'permissions' => \App\Models\Role::modulePermissions(true, 'assign')]);
    Route::put('/permission/update', ['as' => 'muntazim.permissions.update', 'uses' => 'Muntazim\PermissionController@update',
        'permissions' => \App\Models\Role::modulePermissions(true, 'update')]);
    Route::get('/permission/delete/{id}', ['as' => 'muntazim.permissions.delete', 'uses' => 'Muntazim\PermissionController@destroy',
        'permissions' => \App\Models\User::modulePermissions(true, 'delete')]);
    Route::get('/permission/sync', ['as' => 'muntazim.permissions.sync', 'uses' => 'Muntazim\PermissionController@syncPermissions',
        'permissions' => \App\Models\Permission::modulePermissions(true, 'sync')]);
    // Nav
    Route::get('/nav', ['as' => 'muntazim.nav', 'uses' => 'Muntazim\NavController@index',
        'permissions' => \App\Models\Nav::modulePermissions(true, 'manage')]);

    Route::get('/nav/links/{id}', ['as' => 'muntazim.nav.links', 'uses' => 'Muntazim\NavController@links',
        'permissions' => \App\Models\Nav::modulePermissions(true, 'manage')]);
    Route::put('/nav/links/store/{id}', ['as' => 'muntazim.nav.links.store', 'uses' => 'Muntazim\NavController@storeLinks',
        'permissions' => \App\Models\Nav::modulePermissions(true, 'manage')]);

    Route::get('/nav/create', ['as' => 'muntazim.nav.create', 'uses' => 'Muntazim\NavController@create',
        'permissions' => \App\Models\Nav::modulePermissions(true, 'create')]);
    Route::post('/nav/store', ['as' => 'muntazim.nav.store', 'uses' => 'Muntazim\NavController@store',
        'permissions' => \App\Models\Nav::modulePermissions(true, 'create')]);

    Route::get('/nav/edit/{id}', ['as' => 'muntazim.nav.edit', 'uses' => 'Muntazim\NavController@edit',
        'permissions' => \App\Models\Nav::modulePermissions(true, 'edit')]);
    Route::put('/nav/update/{id}', ['as' => 'muntazim.nav.update', 'uses' => 'Muntazim\NavController@update',
        'permissions' => \App\Models\Nav::modulePermissions(true, 'update')]);

    Route::get('/nav/delete/{id}', ['as' => 'muntazim.nav.delete', 'uses' => 'Muntazim\NavController@destroy',
        'permissions' => \App\Models\Nav::modulePermissions(true, 'delete')]);

    // Countries
    Route::get('/countries', ['as' => 'muntazim.countries', 'uses' => 'Muntazim\CountryController@index',
        'permissions' => \App\Models\Country::modulePermissions(true, 'manage')]);

    Route::get('/country/create', ['as' => 'muntazim.countries.create', 'uses' => 'Muntazim\CountryController@create',
        'permissions' => \App\Models\Country::modulePermissions(true, 'create')]);
    Route::post('/country/store', ['as' => 'muntazim.countries.store', 'uses' => 'Muntazim\CountryController@store',
        'permissions' => \App\Models\Country::modulePermissions(true, 'store')]);

    Route::get('/country/edit/{id}', ['as' => 'muntazim.countries.edit', 'uses' => 'Muntazim\CountryController@edit',
        'permissions' => \App\Models\Country::modulePermissions(true, 'edit')]);
    Route::put('/country/update/{id}', ['as' => 'muntazim.countries.update', 'uses' => 'Muntazim\CountryController@update',
        'permissions' => \App\Models\Country::modulePermissions(true, 'update')]);

    Route::get('/country/delete/{id}', ['as' => 'muntazim.countries.delete', 'uses' => 'Muntazim\CountryController@destroy',
        'permissions' => \App\Models\Country::modulePermissions(true, 'delete')]);

    // Cities
    Route::get('/cities/{pid}', ['as' => 'muntazim.cities', 'uses' => 'Muntazim\CityController@index',
        'permissions' => \App\Models\Country::modulePermissions(true, 'manage')]);

    Route::get('/city/create', ['as' => 'muntazim.cities.create', 'uses' => 'Muntazim\CityController@create',
        'permissions' => \App\Models\Country::modulePermissions(true, 'create')]);
    Route::post('/city/store', ['as' => 'muntazim.cities.store', 'uses' => 'Muntazim\CityController@store',
        'permissions' => \App\Models\Country::modulePermissions(true, 'store')]);

    Route::get('/city/edit/{id}', ['as' => 'muntazim.cities.edit', 'uses' => 'Muntazim\CityController@edit',
        'permissions' => \App\Models\Country::modulePermissions(true, 'edit')]);
    Route::put('/city/update/{id}', ['as' => 'muntazim.cities.update', 'uses' => 'Muntazim\CityController@update',
        'permissions' => \App\Models\Country::modulePermissions(true, 'update')]);

    Route::get('/city/delete/{id}', ['as' => 'muntazim.cities.delete', 'uses' => 'Muntazim\CityController@destroy',
        'permissions' => \App\Models\Country::modulePermissions(true, 'delete')]);

    // Categories

    Route::get('/categories/{pid?}', ['as' => 'muntazim.categories', 'uses' => 'Muntazim\CategoryController@index',
        'permissions' => \App\Models\Category::modulePermissions(true, 'manage')]);

app/Models/Role.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use App\Interfaces\Permissions;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class Role extends Model implements Permissions
{
    use Notifiable, SoftDeletes;

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function givePermissionTo(Permission $permission)
    {
        return $this->permissions()->save($permission);
    }

    public function getCreatedAtAttribute($value)
    {
        $datetime = Carbon::createFromFormat('Y-m-d H:i:s', $value);
        return $datetime->format('d M, Y - H:i:s');
    }

    public function getUpdatedAtAttribute($value)
    {
        $datetime = Carbon::createFromFormat('Y-m-d H:i:s', $value);
        return $datetime->format('d M, Y - H:i:s');
    }

    public static function modulePermissions($middleware = false, $route = null)
    {
        if ($middleware) {
            switch ($route) {
                case 'manage':
                case 'show':
                    return array('view_role');
                    break;
                case 'create':
                case 'store':
                    return array('create_role');
                    break;
                case 'edit':
                case 'update':
                case 'assign':
                    return array('edit_role', 'assign_role');
                    break;
                case 'delete':
                    return array('delete_role');
                    break;
                default:
                    return array();
            }
        }
        return array(
            'view_role',
            'create_role',
            'edit_role',
            'assign_role',
            'delete_role',
        );
    }

}

app/Http/Controllers/Muntazim/CinemaController.php
<?php

namespace App\Http\Controllers\Muntazim;

use App\Models\Category;
use App\Models\Cinema;
use Auth;
use File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CinemaController extends MuntazimController
{
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $pid = null)
    {
        $parent = Category::find($pid);

        $field = $request->query('field', null);
        $keyword = $request->query('keyword', null);
        $filters = $request->query('filter', null);
        $data = Cinema::with('city')->whereHas('category', function ($query) use ($pid) {
            $query->where('categories.parent_id', $pid)->with('cities');
        });
        $data = $data->orderBy('created_at', 'ASC')->paginate(12);

        $pageTitle = "All Cinemas";
        $smallTitle = $data->count();
        $breadcrumbs = [
            ['text' => __('faqs.all_categories'), 'url' => route('muntazim.categories')],
            ['text' => $pageTitle],
        ];
        $viewParams = [
            'data' => $data,
            'field' => $field,
            'keyword' => $keyword,
            'filters' => $filters,
            'parent' => $parent,
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
            'smallTitle' => $smallTitle,
        ];
        return view('muntazim.cinema.index', $viewParams);
    }

    public function edit(Request $request, $id)
    {
        $modal = Cinema::with('category')->find($id);
        $pageTitle = "Edit Cinema";
        $smallTitle = '';
        $breadcrumbs = [];
        $viewParams = [
            'modal' => $modal,
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
            'smallTitle' => $smallTitle,
            'src' => $request->input('src')
        ];

        return view('muntazim.cinema.edit', $viewParams);
    }

    public function update(Request $request, $id)
    {
        $modal = Cinema::find($id);
        $modal->address = $request->input('address');
        $modal->name = $request->input('name');
        $modal->front = $request->input('front');
        $modal->back = $request->input('back');
        $modal->gallery = $request->input('gallery');
        $modal->active = $request->input('active');
        $modal->public = $request->input('public');
        $modal->featured = $request->input('featured');
        if ($modal->save()) {
            Session::flash('success', 'Cinema has been updated');
            return redirect()->back();
        }
    }

    public function media(Request $request, $id)
    {
        $modal = Cinema::with('category', 'media')->find($id);
        $pageTitle = "Edit Media";
        $smallTitle = '';
        $breadcrumbs = [];
        $viewParams = [
            'modal' => $modal,
            'breadcrumbs' => $breadcrumbs,
            'type' => 'cinema',
            'pageTitle' => $pageTitle,
            'smallTitle' => $smallTitle,
            'src' => $request->input('src')
        ];

        return view('muntazim.media.edit', $viewParams);
    }
}

app/Http/Controllers/Muntazim/HomeController.php
<?php
namespace App\Http\Controllers\Muntazim;
use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;
use App\Models\User;
use Auth;
class HomeController extends Controller{
    public function __construct(){
        $this->middleware('auth');
    }
    public function index(Request $request){
        $pageTitle = 'Dashboard';
        $viewParams = [
            'pageTitle' => $pageTitle,
        ];
		return view('muntazim.index', ['pageTitle' => __('general.dashboard_title')]);
    }
}

app/Http/Controllers/Muntazim/MuntazimController.php
<?php

namespace App\Http\Controllers\Muntazim;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MuntazimController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /*public function index(Request $request)
    {
        $pageTitle = 'Dashboard';
        $viewParams = [
            'pageTitle' => $pageTitle,
        ];
        return view('muntazim.index', ['pageTitle' => __('meme.dashboard_title')]);
    }*/
}

resources/views/muntazim/roles/assign.blade.php
@extends('layouts.app')
@section('pageTitle', $pageTitle)
@section('content')
    <section class="section py-6">
        <div class="container">
            <form method="post" action="{{route('muntazim.roles.update',[$parent_id,'for'=>$for])}}"
                  class="input-border"
                  autocomplete="off" enctype="multipart/form-data">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="row gap-y">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>{{__('general.permissions')}}</label>
                            <select class="form-control selectpicker show-menu-arrow" name="roles[]"
                                    data-live-search="true" data-selected-text-format="count > 3" data-size="10"
                                    data-actions-box="true" data-placeholder="{{__('general.permissions')}}" multiple>
                                required multiple>
                                @foreach($model as $key=>$value)
                                    <option value="{{$key}}">{{$value}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="pull-right">
                    <button type="submit" class="btn btn-label btn-primary">
                        <label><i class="fa fa-save"></i></label> {{__('general.update')}}
                    </button>
                </div>
            </form>
        </div>
    </section>
@stop

resources/views/muntazim/roles/create.blade.php
@extends('layouts.app')
@section('pageTitle', $pageTitle)
@section('content')
    <section class="section py-6">
        <div class="container">
            <form method="post" action="{{route('muntazim.roles.store')}}" class="input-border"
                  autocomplete="off" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="row gap-y">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>{{__('general.name')}}</label>
                            <input type="text" name="name" class="form-control" placeholder="{{__('general.name')}}"
                                   value="{{old('name')}}" autofocus required>
                        </div>
                        <div class="form-group">
                            <label>{{__('general.label')}}</label>
                            <input type="text" name="label" class="form-control" placeholder="{{__('general.label')}}"
                                   value="{{old('label')}}">
                        </div>
                        <div class="form-group">
                            <label>{{__('general.permissions')}}</label>
                            <select class="form-control selectpicker show-menu-arrow" name="permissions[]"
                                    data-live-search="true" data-selected-text-format="count > 3" data-size="10"
                                    data-actions-box="true" data-placeholder="{{__('general.permissions')}}" multiple>
                                    required multiple>
                                @foreach($permissions as $key=>$value)
                                    <option value="{{$key}}">{{$value}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="active" class="custom-control-input" value="1"
                                   @if(old('active')) checked @endif>
                            <label class="custom-control-label">{{__('general.active')}}</label>
                        </div>
                    </div>
                </div>
                <div class="pull-right">
                    <a href="{{route('muntazim.roles')}}"
                       class="btn btn-label btn-secondary">
                        <label><i class="fa fa-table"></i></label> {{__('general.all_roles')}}
                    </a>
                    <button type="submit" class="btn btn-label btn-primary">
                        <label><i class="fa fa-save"></i></label> {{__('general.create')}}
                    </button>
                </div>
            </form>
        </div>
    </section>
@stop

resources/views/muntazim/roles/edit.blade.php
@extends('layouts.app')
@section('pageTitle', $pageTitle)
@section('content')
    <section class="section py-6">
        <div class="container">
            <form method="post" action="{{route('muntazim.roles.update', $role->id)}}" class="input-border"
                  autocomplete="off" enctype="multipart/form-data">
                {{ method_field('PUT') }}
                {{ csrf_field() }}

                <div class="row gap-y">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>{{__('general.name')}}</label>
                            <input type="text" name="name" class="form-control" placeholder="{{__('general.name')}}"
                                   value="{{old('name',$role->name)}}" disabled="disabled" autofocus required>
                        </div>
                        <div class="form-group">
                            <label>{{__('general.label')}}</label>
                            <input type="text" name="label" class="form-control" placeholder="{{__('general.label')}}"
                                   value="{{old('label',$role->label)}}" disabled="disabled">
                        </div>
                        <div class="form-group">
                            <label>{{__('general.permissions')}}</label>
                            @php
                               $already_permissions =  $role->permissions->pluck('id')->toArray();
                            @endphp
                            <select class="form-control selectpicker show-menu-arrow" name="permissions[]"
                                    data-live-search="true" data-selected-text-format="count > 3" data-size="10"
                                    data-actions-box="true" data-placeholder="{{__('general.permissions')}}" required multiple>
                                @foreach($permissions as $key=>$value)
                                    @php
                                       if (in_array($key,$already_permissions)){
                                         $selected ="selected";
                                       }else{
                                         $selected ="";
                                       }
                                    @endphp
                                    <option value="{{$key}}" {{$selected}}>{{$value}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="active" class="custom-control-input" value="1"
                                   @if($role->active) checked @endif>
                            <label class="custom-control-label">{{__('general.active')}}</label>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-12">
                        <div class="pull-right">
                            <a href="{{route('muntazim.roles')}}"
                               class="btn btn-label btn-secondary">
                                <label><i class="fa fa-table"></i></label> {{__('general.all_roles')}}
                            </a>
                            <button type="submit" class="btn btn-label btn-primary">
                                <label><i class="fa fa-save"></i></label> {{__('general.update')}}
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
@stop

resources/views/muntazim/roles/permissions.blade.php
@extends('layouts.app')
@section('pageTitle', $pageTitle)
@section('content')
    <section class="section py-6">
        <div class="container">
            <div class="box box-primary">
                <div class="box-body">

                    @if($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @if ($successMessage = \Illuminate\Support\Facades\Session::get('successMessage'))
                        <div class="callout callout-success">
                            <p>{{ $successMessage }}</p>
                        </div>
                    @endif

                    <table id="accessListTbl" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Label</th>
                            <th>Date Created</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($permissions as $permission)
                            <tr>
                                <td>{{$permission->name}}</td>
                                <td>{{$permission->label}}</td>
                                <td>{{$permission->created_at}}</td>
                            </tr>
                        @endforeach
                        </tbody>

                    </table>
                </div><!-- /.box-body -->
                <div class="box-footer with-border">
                    <div class="pull-right">
                        {{ $permissions->links() }}
                    </div>
                </div><!-- /.box-header -->
            </div><!-- /.box -->
        </div>
    </section>
@stop
@section('pageScript')
@stop

resources/views/muntazim/roles/show.blade.php
@extends('layouts.app')
@section('pageTitle', $pageTitle)
@section('content')
    <section class="section py-6">
        <div class="container">
            <div class="row gap-y">
                <div class="col-md-4">
                    <h3 class="text-center">{{$model->label}}</h3>
                    <ul class="list-group">
                        <li class="list-group-item">{{__('general.name')}} <span
                                    class="badge pull-right">{{$model->name}}</span></li>
                        <li class="list-group-item">{{__('general.label')}} <span
                                    class="badge pull-right">{{$model->label}}</span></li>
                        <li class="list-group-item">{{__('general.active')}}
                            @if($model->active)
                                <span class="badge badge-success pull-right">Active</span>
                            @else
                                <span class="badge badge-danger pull-right">In Active</span>
                            @endif
                        </li>
                        <li class="list-group-item">{{__('general.created_date')}} <span
                                    class="badge pull-right">{{$model->created_at}}</span></li>
                        <li class="list-group-item">{{__('general.updated_date')}} <span
                                    class="badge pull-right">{{$model->updated_at}}</span></li>
                        <li class="list-group-item text-center">
                            @can('update', $model)
                                <a class="btn btn-xs btn-primary btn-block"
                                   href="{{route('muntazim.roles.edit',[$model->id])}}">{{__('general.edit')}}</a>
                            @endcan
                        </li>
                    </ul>
                </div>
                <div class="col-md-8">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#users">{{__('general.users')}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#permissions">{{__('general.permissions')}}</a>
                        </li>
                    </ul>
                    <div class="tab-content p-4">
                        <div class="tab-pane fade show active text-center" id="users">
                            <p class="text-center">Total Users of <strong>{{$model->label}}</strong>
                                are <strong>{{$model->users()->count()}}</strong></p>
                            <table class="table table-striped">
                                <tbody>
                                <tr>
                                    <th style="width: 10px">#</th>
                                    <th>Name</th>
                                </tr>
                                @foreach($model->users as $user)
                                    <tr>
                                        <td>{{$user->id}}</td>
                                        <td>{{$user->name}}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="permissions">
                            <p class="text-center">Total Permissioins of <strong>{{$model->label}}</strong>
                                are <strong>{{$model->permissions()->count()}}</strong></p>
                            <table class="table table-striped">
                                <tbody>
                                <tr>
                                    <th style="width: 10px">#</th>
                                    <th>Name</th>
                                    <th>Label</th>
                                </tr>
                                @foreach($model->permissions as $permission)
                                    <tr>
                                        <td>{{$permission->id}}</td>
                                        <td>{{$permission->name}}</td>
                                        <td>{{$permission->label}}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop